"""Loose stubs for folium (Pyright import resolution)."""
from typing import Any

class Map:
    def __init__(self, location: Any = None, zoom_start: int = 10, tiles: Any = None, **kwargs: Any) -> None: ...
    def save(self, outfile: str, **kwargs: Any) -> None: ...
    def add_child(self, child: Any, **kwargs: Any) -> Any: ...

class Choropleth:
    def __init__(self, **kwargs: Any) -> None: ...
    def add_to(self, m: Any) -> Any: ...

class CircleMarker:
    def __init__(self, location: Any = None, radius: Any = None, **kwargs: Any) -> None: ...
    def add_to(self, m: Any) -> Any: ...
